package com.frc.teacherhelper.entity;
// Generated 2016-7-5 23:47:38 by Hibernate Tools 3.5.0.Final

/**
 * Problem generated by hbm2java
 */
public class Problem implements java.io.Serializable {

	private Integer id;
	private Integer subjectid;
	private Integer grade;
	private Integer type;
	private String description;
	private String optionA;
	private String optionB;
	private String optionC;
	private String optionD;
	private String optionE;
	private String optionF;
	private String answer;
	private String analysis;
	private Integer point;
	private String testitem;
	private String creator;
	private String createtime;

	public Problem() {
	}

	public Problem(Integer subjectid, Integer grade, Integer type, String description, String optionA, String optionB,
			String optionC, String optionD, String optionE, String optionF, String answer, String analysis,
			Integer point, String testitem, String creator, String createtime) {
		this.subjectid = subjectid;
		this.grade = grade;
		this.type = type;
		this.description = description;
		this.optionA = optionA;
		this.optionB = optionB;
		this.optionC = optionC;
		this.optionD = optionD;
		this.optionE = optionE;
		this.optionF = optionF;
		this.answer = answer;
		this.analysis = analysis;
		this.point = point;
		this.testitem = testitem;
		this.creator = creator;
		this.createtime = createtime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getSubjectid() {
		return this.subjectid;
	}

	public void setSubjectid(Integer subjectid) {
		this.subjectid = subjectid;
	}

	public Integer getGrade() {
		return this.grade;
	}

	public void setGrade(Integer grade) {
		this.grade = grade;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getOptionA() {
		return this.optionA;
	}

	public void setOptionA(String optionA) {
		this.optionA = optionA;
	}

	public String getOptionB() {
		return this.optionB;
	}

	public void setOptionB(String optionB) {
		this.optionB = optionB;
	}

	public String getOptionC() {
		return this.optionC;
	}

	public void setOptionC(String optionC) {
		this.optionC = optionC;
	}

	public String getOptionD() {
		return this.optionD;
	}

	public void setOptionD(String optionD) {
		this.optionD = optionD;
	}

	public String getOptionE() {
		return this.optionE;
	}

	public void setOptionE(String optionE) {
		this.optionE = optionE;
	}

	public String getOptionF() {
		return this.optionF;
	}

	public void setOptionF(String optionF) {
		this.optionF = optionF;
	}

	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	public String getAnalysis() {
		return this.analysis;
	}

	public void setAnalysis(String analysis) {
		this.analysis = analysis;
	}

	public Integer getPoint() {
		return this.point;
	}

	public void setPoint(Integer point) {
		this.point = point;
	}

	public String getTestitem() {
		return this.testitem;
	}

	public void setTestitem(String testitem) {
		this.testitem = testitem;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public String getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

}
