package com.frc.teacherhelper.entity;
// Generated 2016-8-4 23:17:06 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Profile generated by hbm2java
 */
public class Profile implements java.io.Serializable {

	private Integer idprofile;
	private String username;
	private String password;
	private Date registerDate;
	private int status;
	private String mailAddress;
	private String nickname;
	private int type;

	public Profile() {
	}

	public Profile(String username, String password, int status, int type) {
		this.username = username;
		this.password = password;
		this.status = status;
		this.type = type;
	}

	public Profile(String username, String password, Date registerDate, int status, String mailAddress, String nickname,
			int type) {
		this.username = username;
		this.password = password;
		this.registerDate = registerDate;
		this.status = status;
		this.mailAddress = mailAddress;
		this.nickname = nickname;
		this.type = type;
	}

	public Integer getIdprofile() {
		return this.idprofile;
	}

	public void setIdprofile(Integer idprofile) {
		this.idprofile = idprofile;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getRegisterDate() {
		return this.registerDate;
	}

	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getMailAddress() {
		return this.mailAddress;
	}

	public void setMailAddress(String mailAddress) {
		this.mailAddress = mailAddress;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

}
