package com.frc.teacherhelper.entity;
// Generated 2016-8-4 23:17:06 by Hibernate Tools 3.5.0.Final

/**
 * Testitem generated by hbm2java
 */
public class Testitem implements java.io.Serializable {

	private Integer id;
	private Integer level;
	private Integer parentId;
	private String seq;
	private String content;
	private String creator;
	private String createtime;
	private Integer subjectid;
	private String grade;
	private Integer unit;

	public Testitem() {
	}

	public Testitem(Integer level, Integer parentId, String seq, String content, String creator, String createtime,
			Integer subjectid, String grade, Integer unit) {
		this.level = level;
		this.parentId = parentId;
		this.seq = seq;
		this.content = content;
		this.creator = creator;
		this.createtime = createtime;
		this.subjectid = subjectid;
		this.grade = grade;
		this.unit = unit;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public String getSeq() {
		return this.seq;
	}

	public void setSeq(String seq) {
		this.seq = seq;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public String getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	public Integer getSubjectid() {
		return this.subjectid;
	}

	public void setSubjectid(Integer subjectid) {
		this.subjectid = subjectid;
	}

	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	public Integer getUnit() {
		return this.unit;
	}

	public void setUnit(Integer unit) {
		this.unit = unit;
	}

}
