package com.frc.teacherhelper.entity;
// Generated 2016-7-5 23:47:38 by Hibernate Tools 3.5.0.Final

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;
	private Integer status;
	private Integer role;
	private String email;
	private String name;
	private String mobile;
	private String grade;
	private Integer subjectid;
	private String registerdate;

	public User() {
	}

	public User(String username, String password, Integer status, Integer role, String email, String name,
			String mobile, String grade, Integer subjectid, String registerdate) {
		this.username = username;
		this.password = password;
		this.status = status;
		this.role = role;
		this.email = email;
		this.name = name;
		this.mobile = mobile;
		this.grade = grade;
		this.subjectid = subjectid;
		this.registerdate = registerdate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getRole() {
		return this.role;
	}

	public void setRole(Integer role) {
		this.role = role;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	public Integer getSubjectid() {
		return this.subjectid;
	}

	public void setSubjectid(Integer subjectid) {
		this.subjectid = subjectid;
	}

	public String getRegisterdate() {
		return this.registerdate;
	}

	public void setRegisterdate(String registerdate) {
		this.registerdate = registerdate;
	}

}
